excluded: # paths to ignore during linting. Takes precedence over `included`.
  - MoneyTapAssignment/Pods/
  - Pods/
  - MoneyTapAssignment/Global/AppDelegate.swift
  - Tests
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - large_tuple
  - file_length
  - nesting
